/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChatScreen.java
 *
 * Created on Dec 11, 2013, 2:05:39 AM
 */

package cloudpresenter.gui;

import cloudpresenter.model.Device;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Nawanjana
 */
public class ChatScreen extends javax.swing.JFrame {

    private final Device otherend;
    DefaultListModel dlm;
    /** Creates new form ChatScreen */
    public ChatScreen(Device otherend) {
        initComponents();
        this.setLocationRelativeTo(getRootPane());
        this.getRootPane().setDefaultButton(btnSubmit);
        this.otherend = otherend;
        dlm = new DefaultListModel();
        lstChat.setModel(dlm);
        lblUser.setText(otherend.getDeviceName());
        this.setTitle("Chat with : "+otherend.getDeviceName());
    }


    public String getOtherEndIP(){
        return otherend.getIpAddress();
    }

    public void inputChat(String chat){
        
        dlm.add(dlm.getSize(), otherend.getDeviceName()+" :"+chat);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstChat = new javax.swing.JList();
        txtChatInput = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        lblUser.setText("User Name");

        jScrollPane1.setViewportView(lstChat);

        btnSubmit.setText("Enter");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(lblUser)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtChatInput, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String sendchat = txtChatInput.getText();
        Socket theSocket;
        try {
            theSocket = new Socket(otherend.getIpAddress(), 6062);
            DataOutputStream dOut = new DataOutputStream(theSocket.getOutputStream());
            dOut.writeUTF(sendchat);
            dOut.close();
            theSocket.close();
            dlm.add(dlm.getSize(), "You :"+sendchat);
            txtChatInput.setText("");
        } catch (UnknownHostException ex) {
            System.err.println(ex);
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatScreen(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList lstChat;
    private javax.swing.JTextField txtChatInput;
    // End of variables declaration//GEN-END:variables

}
