/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewImage.java
 *
 * Created on Sep 16, 2013, 2:35:42 PM
 */
package cloudpresenter.gui;

import cloudpresenter.imagestream.StreamImagesOnScreen;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JRootPane;

/**
 *
 * @author Nawanjana
 */
public class ViewImageUI extends javax.swing.JFrame {

    private final StreamImagesOnScreen control;

    /** Creates new form ViewImage */
//    public ViewImageUI(ImageStream tstream) {
    public ViewImageUI(StreamImagesOnScreen control) {
        this.setLocationRelativeTo(getRootPane());
        // this.setUndecorated(true);
//        this.stream = tstream;
        initComponents();
//        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        final ViewImageUI screen = this;
        this.control = control;
//        new Thread(new Runnable() {
//            public void run() {
//                boolean tryagain = false;
//                ScreenFrame scfr = null;
//                do {
//                    try {
//                        scfr = stream.getNewest();
//                        tryagain = false;
//                    } catch (NoSuchFieldException ex) {
//                        tryagain = true;
//                    } catch (ArrayIndexOutOfBoundsException arrayIndexOutOfBoundsException) {
//                        tryagain = true;
//                    }
//                } while (tryagain);
//                screen.setImage(scfr.image);
//                System.out.println("New Image:"+scfr.timestamp);
//                screen.repaint();
//                if (isVisible()) {
//                    screen.setVisible(true);
//                }
//            }
//        }).start();
        //this.setBorder(BorderFactory.createEmptyBorder(N, N, N, N));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                // new ViewImageUI().setVisible(true);
            }
        });
    }

    @Override
    public void setVisible(boolean b) {
        if (!b) {
            control.interruptScreen();
        }
        super.setVisible(b);
    }

    public void setImage(BufferedImage img) {
        double screenRatio = ((double) jLabel1.getWidth()) / ((double) jLabel1.getHeight());
        double imageRatio = ((double) img.getWidth()) / ((double) img.getHeight());
        double scale = ((double) (jLabel1.getWidth()) / (double) (img.getWidth()));
        if ((screenRatio / imageRatio) > 1) {
            scale = ((double) (jLabel1.getHeight()) / (double) (img.getHeight()));
        }
        jLabel1.setIcon(new ImageIcon(img.getScaledInstance((int) (img.getWidth() * scale), (int) (img.getHeight() * scale), Image.SCALE_SMOOTH)));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
