/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeviceShareSelect.java
 *
 * Created on Dec 9, 2013, 8:53:52 PM
 */
package cloudpresenter.gui.panels;

import cloudpresenter.controller.ChatManager;
import cloudpresenter.controller.ImageStreamManager;
import cloudpresenter.gui.ChatScreen;
import cloudpresenter.gui.FileProgress;
import cloudpresenter.model.Device;
import cloudpresenter.network.ScreenSharingServer;
import cloudpresenter.network.SendAFile;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Nawanjana
 */
public class DeviceShareSelect extends javax.swing.JPanel {

    private Device selected;

    /** Creates new form DeviceShareSelect */
    public DeviceShareSelect(Device deviceName) {
        initComponents();
        selected = deviceName;
        jLabel1.setText(selected.getDeviceName());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnScreen = new javax.swing.JButton();
        btnChat = new javax.swing.JButton();
        btnFile = new javax.swing.JButton();

        jLabel1.setText("Device Name");

        btnScreen.setText("Screen Share");
        btnScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScreenActionPerformed(evt);
            }
        });

        btnChat.setText("Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });

        btnFile.setText("File Share");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnChat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnScreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChat)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScreenActionPerformed
        if (!selected.getIpAddress().isEmpty()) {
            ScreenSharingServer server = new ScreenSharingServer(selected.getIpAddress(), false);
            ImageStreamManager.addNewImageStream(server, selected.getDeviceName());
            server.start();
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "This user is not online!", "Offline", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnScreenActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        if (!selected.getIpAddress().isEmpty()) {
            ChatScreen screen = new ChatScreen(selected);
            ChatManager.addNewChatStream(screen);
            screen.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "This user is not online!", "Offline", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnChatActionPerformed

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        if (!selected.getIpAddress().isEmpty()) {
            JFileChooser filechooser = new JFileChooser();
            filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int resultVal = filechooser.showOpenDialog(null);
            if (resultVal == JFileChooser.OPEN_DIALOG) {
                File file = filechooser.getSelectedFile();
                FileProgress prg = new FileProgress("Sending " + file.getName(), file.length());
                SendAFile sendafile = new SendAFile(file, selected, prg);
                prg.setVisible(true);
                sendafile.start();
            }
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "This user is not online!", "Offline", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnFileActionPerformed

    public void setDeviceName() {
        jLabel1.setText(selected.getDeviceName());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnScreen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
