/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeviceShareSelect.java
 *
 * Created on Dec 9, 2013, 8:53:52 PM
 */
package cloudpresenter.gui.panels;

import cloudpresenter.controller.ChatManager;
import cloudpresenter.gui.ChatScreen;
import cloudpresenter.gui.FileProgress;
import cloudpresenter.gui.MainScreen;
import cloudpresenter.model.Device;
import cloudpresenter.model.Group;
import cloudpresenter.network.ScreenSharingServer;
import cloudpresenter.network.SendAFile;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Nawanjana
 */
public class GroupShareSelect extends javax.swing.JPanel {

    private Group selected;

    /** Creates new form DeviceShareSelect */
    public GroupShareSelect(Group group) {
        initComponents();
        selected = group;
        jLabel1.setText(selected.getGroupID());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnScreen = new javax.swing.JButton();
        btnFile = new javax.swing.JButton();

        jLabel1.setText("Device Name");

        btnScreen.setText("Screen Share");
        btnScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScreenActionPerformed(evt);
            }
        });

        btnFile.setText("File Share");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnScreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScreenActionPerformed
        ScreenSharingServer server = new ScreenSharingServer(selected.getMcastIP(),true);
        server.start();
    }//GEN-LAST:event_btnScreenActionPerformed

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        MainScreen.rUDPms.joinGroup(selected);
    }//GEN-LAST:event_btnFileActionPerformed

    public void setDeviceName() {
        jLabel1.setText(selected.getGroupID());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnScreen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
